name: Publish package to the Maven Central Repository
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 'latest'
      - name: "Build JAR files"
        run: lein uberjar
      - name: "Generate pom.xml"
        run: lein pom
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Add release version to GITHUB_ENV
        id: get-version
        run: |
          V=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tr -d '\n\r\t ')
          echo "version=$V" >> $GITHUB_ENV
      - name: Deploy Javadoc to GH pages (latest dir)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/javadoc-out
          destination_dir: docs/latest
      - name: Deploy Javadoc to GH pages (release dir)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/javadoc-out
          destination_dir: docs/${{ env.version }}
      - name: Publish package
        run: mvn --batch-mode -Dsource=1.8 -Dtarget=1.8 -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8 deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}