name: test

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.3
        with:
          lein: 'latest'
      - run: lein kaocha
      - run: lein kondo
      - run: lein fmt