name: test

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 'latest'
      - run: lein kaocha
      - run: lein kondo
      - run: lein fmt
      - name: Lint javadoc
        run: ./scripts/javadoc.sh
